// src/lib/components/AudioPlayer.tsx
import { useRef, useState } from 'react';
import type { MouseEvent, PointerEvent as ReactPointerEvent } from 'react';
import Button from './form/Button';

interface Props {
	id?: string;
	url?: string;
}

export default function AudioPlayer({ id = '', url = '' }: Props) {
	const [time, setTime] = useState(0);
	const [duration, setDuration] = useState(0);
	const [paused, setPaused] = useState(true);
	const audioRef = useRef<HTMLAudioElement | null>(null);

	function playPause(e: MouseEvent<HTMLButtonElement>) {
		const current = audioRef.current;
		if (current) {
			e.preventDefault();
			current.volume = 0.25;
			const audios = document.getElementsByTagName('audio');
			for (let index = 0; index < audios.length; index++) {
				audios[index].pause();
			}
			if (paused) current.play();
			else current.pause();
		}
	}

	function seek(clientX: number, target: HTMLInputElement) {
		const { left, width } = target.getBoundingClientRect();
		let p = (clientX - left) / width;
		if (p < 0) p = 0;
		if (p > 1) p = 1;
		const newTime = p * duration;
		setTime(newTime);
		if (audioRef.current) audioRef.current.currentTime = newTime;
	}

	function handlePointerDown(e: ReactPointerEvent<HTMLInputElement>) {
		const target = e.currentTarget;
		seek(e.clientX, target);
		const onPointerMove = (moveEvent: PointerEvent) => seek(moveEvent.clientX, target);
		const onPointerUp = () => {
			target.removeEventListener('pointermove', onPointerMove);
			target.removeEventListener('pointerup', onPointerUp);
		};
		target.addEventListener('pointermove', onPointerMove);
		target.addEventListener('pointerup', onPointerUp);
	}

	if (!url) return null;

	return (
		<>
			<audio
				ref={(el) => {
					audioRef.current = el;
					if (el) el.volume = 0.4;
				}}
				id={id}
				className=" bg-zinc-950 rounded"
				preload="none"
				onTimeUpdate={(e) => setTime(e.currentTarget.currentTime)}
				onDurationChange={(e) => setDuration(e.currentTarget.duration)}
				onPlay={() => setPaused(false)}
				onPause={() => setPaused(true)}
				onEnded={() => {
					setTime(0);
					if (audioRef.current) audioRef.current.currentTime = 0;
				}}
			>
				<source src={url} />
			</audio>
			<div className="w-full flex items-center gap-x-2">
				<input
					type="range"
					className="flex-1"
					min="0"
					max={duration}
					value={time}
					onChange={() => {}}
					onPointerDown={handlePointerDown}
				/>
				<div className="w-8 h-8">
					<Button
						icon={paused ? 'ph:play' : 'ph:pause'}
						onClick={playPause}
						variant={paused ? 'primary' : 'info'}
					/>
				</div>
			</div>
		</>
	);
}

// src/lib/components/AudioPlayer.svelte
<script lang="ts">
	import Button from './form/Button.svelte';

	export let id = '';
	export let url = '';
	let time = 0;
	let duration = 0;
	let paused = true;
	let current: HTMLAudioElement | undefined;

	function playPause(
		e:
			| MouseEvent
			| (Event & {
					currentTarget: EventTarget & HTMLAudioElement;
			  })
	) {
		if (current) {
			e.preventDefault();
			current.volume = 0.25;
			const audios = document.getElementsByTagName('audio');

			for (let index = 0; index < audios.length; index++) {
				audios[index].pause();
			}
			if (paused) current.play();
			else current.pause();
		}
	}

	function setTime(
		e: PointerEvent & {
			currentTarget: EventTarget & HTMLInputElement;
		}
	) {
		const { left, width } = e.currentTarget.getBoundingClientRect();

		let p = (e.clientX - left) / width;
		if (p < 0) p = 0;
		if (p > 1) p = 1;

		time = p * duration;

		// @ts-ignore
		e.currentTarget.addEventListener('pointermove', setTime);
	}
	function removeListener(
		e: PointerEvent & {
			currentTarget: EventTarget & HTMLInputElement;
		}
	) {
		// @ts-ignore
		e.currentTarget.removeEventListener('pointermove', setTime);
	}
</script>

{#if !!url}
	<audio
		bind:currentTime={time}
		bind:duration
		bind:paused
		bind:this={current}
		volume={0.4}
		{id}
		class=" bg-zinc-950 rounded"
		preload="none"
		on:ended={() => {
			time = 0;
		}}
	>
		<source src={url} />
	</audio>
	<div class="w-full flex items-center gap-x-2">
		<input
			type="range"
			class="flex-1"
			min="0"
			max={duration}
			value={time}
			on:pointerdown={setTime}
			on:pointerup={removeListener}
		/>
		<div class="w-8 h-8">
			<Button
				icon={paused ? 'ph:play' : 'ph:pause'}
				onClick={playPause}
				variant={paused ? 'primary' : 'info'}
			/>
		</div>
	</div>
{/if}
